dist: trusty
sudo: required

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox


language: node_js
node_js:
  - "8"
  - "10"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - stty cols 80

install:
  - yarn

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

script:
  - yarn lint
  - yarn build

jobs:
  include:
    # - yarn test:unit
    - stage: test
      if: branch IN (e2e/cafe/install)
      script:
        - yarn cafe:time
        # - yarn test:e2e:ci
